---
- name: create NFS folder "/export/NFS"
  file:
    path: /export/NFS
    state: directory
    mode: '0755'

- name: configure "nfs"
  template:
    src: exports.j2
    dest: /etc/exports
    owner: root
    group: root
    mode: '0644'
  notify:
    - restart nfs
