---

- name: Update repositories cache and install "dnsmasq" package
  apt:
    name: dnsmasq
    state: present
    update_cache: yes

- name: configure "dnsmask"
  template:
    src: dnsmasq.conf.j2
    dest: /etc/dnsmasq.conf
    owner: root
    group: root
    mode: '0644'
  notify:
    - restart dnsmasq

