---
- name: Configure "mariadb"
  template:
    src: my.cnf.j2
    dest: /etc/mysql/my.cnf
    owner: root
    group: root
    mode: '0644'
  #notify:
  #  - restart mariadb

- name: Install dependencies 1/2
  apt:
    name: 
      - python-pip
      - python-pymysql 
      - python-setuptools

- name: Install dependencies 2/2
  pip:
    name: PyMySQL

- name: create export "DATA" folders
  file:
    path: "{{ item }}"
    mode: '0755'
    state: directory
  loop:
    - /export/DATA
